apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: dev
spec:
  releaseName: redis
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: bitnami/redis
        name: redis
        namespace: dev
      version: "21.0.3"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3